#!/usr/bin/env node
/**
 * Re-download the self-hosted fonts and regenerate their @font-face rules.
 * ----------------------------------------------------------------------------
 * The app used to link fonts.googleapis.com, the last render-blocking resource
 * on cold boot. The families are now served from `fonts/` and declared at the
 * top of `style.css`.
 *
 * Run this when a family, a weight range, or a subset changes:
 *
 *     node scripts/fetch-fonts.mjs           # writes fonts/ + prints the CSS
 *     node scripts/fetch-fonts.mjs --check   # verifies what's on disk, no writes
 *
 * It asks Google for VARIABLE fonts, so each family is one file per subset
 * rather than one per weight. It keeps `latin` and `latin-ext` only: every
 * other subset (cyrillic, greek, vietnamese) is dead weight for an
 * English-language app, and `latin` already covers the accented characters
 * the food log actually produces, since U+0000-00FF holds e-acute, n-tilde
 * and c-cedilla.
 *
 * The @font-face block is PRINTED, not spliced into style.css. Editing that
 * file by machine risks clobbering the three hand-maintained layers documented
 * at the top of it; paste the output over the existing block instead.
 *
 * Fonts are SIL Open Font License 1.1.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = path.join(ROOT, "fonts");

/** A modern UA is required, or Google serves ttf instead of woff2. */
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

/** Weight ranges must stay in step with what style.css actually asks for. */
const FAMILIES = {
  Inter: { query: "Inter:wght@400..700", weight: "400 700" },
  Literata: { query: "Literata:opsz,wght@7..72,600..700", weight: "600 700" },
  "JetBrains Mono": { query: "JetBrains+Mono:wght@500..700", weight: "500 700" },
};

const SUBSETS = ["latin", "latin-ext"];
const slug = (family) => family.toLowerCase().replace(/\s+/g, "-");

async function fetchCss() {
  const url =
    "https://fonts.googleapis.com/css2?" +
    Object.values(FAMILIES).map((f) => `family=${f.query}`).join("&") +
    "&display=swap";
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
  return res.text();
}

/**
 * Split the stylesheet on its `/* subset *\/` comments. Each block carries one
 * family, one src and one unicode-range.
 */
function parseFaces(css) {
  const parts = css.split(/\/\*\s*([a-z0-9-]+)\s*\*\//i).slice(1);
  const faces = [];
  for (let i = 0; i < parts.length; i += 2) {
    const subset = parts[i];
    const block = parts[i + 1] || "";
    const family = block.match(/font-family:\s*['"]([^'"]+)['"]/)?.[1];
    const url = block.match(/src:\s*url\(([^)]+)\)/)?.[1];
    const unicodeRange = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    if (!family || !url || !SUBSETS.includes(subset)) continue;
    if (!FAMILIES[family]) continue;
    faces.push({ subset, family, url, unicodeRange, file: `${slug(family)}-${subset}.woff2` });
  }
  return faces;
}

function renderCss(faces) {
  const header = `/* ---------------------------------------------------------------------------
   Self-hosted fonts. Generated by scripts/fetch-fonts.mjs — see that file
   before editing by hand.
   --------------------------------------------------------------------------- */
`;
  return (
    header +
    faces
      .map(
        (f) => `
@font-face {
  font-family: "${f.family}";
  font-style: normal;
  font-weight: ${FAMILIES[f.family].weight};
  font-display: swap;
  src: url("fonts/${f.file}") format("woff2");
  unicode-range: ${f.unicodeRange};
}
`
      )
      .join("")
  );
}

const check = process.argv.includes("--check");
const css = await fetchCss();
const faces = parseFaces(css);

const expected = Object.keys(FAMILIES).length * SUBSETS.length;
if (faces.length !== expected) {
  console.error(`Expected ${expected} faces, parsed ${faces.length}. Google changed the response shape.`);
  process.exit(1);
}

if (check) {
  let bad = 0;
  for (const f of faces) {
    const target = path.join(FONT_DIR, f.file);
    if (!fs.existsSync(target)) {
      console.error(`MISSING ${f.file}`);
      bad++;
      continue;
    }
    // wOF2 magic number. A truncated or HTML-error download fails here.
    const magic = fs.readFileSync(target).subarray(0, 4).toString("hex");
    if (magic !== "774f4632") {
      console.error(`NOT WOFF2 ${f.file} (magic ${magic})`);
      bad++;
    }
  }
  console.log(bad ? `${bad} problem(s).` : `All ${faces.length} font files present and valid.`);
  process.exit(bad ? 1 : 0);
}

fs.mkdirSync(FONT_DIR, { recursive: true });
for (const f of faces) {
  const res = await fetch(f.url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${f.file}: ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.subarray(0, 4).toString("hex") !== "774f4632") throw new Error(`${f.file}: not woff2`);
  fs.writeFileSync(path.join(FONT_DIR, f.file), buf);
  console.error(`wrote fonts/${f.file} (${(buf.length / 1024).toFixed(0)}KB)`);
}

console.error("\nPaste the block below over the @font-face rules at the top of style.css:\n");
console.log(renderCss(faces));
